### ISSUE TITLE
Issue with php 7.1

### ISSUE THREAD

**Issue by HOSTED-POWER** [cytopia/check_php#1]
Hi,

With php 7.1 it gives warnings about updates

[WARN] PHP 7.1.0 has warnings: Updates available | 'OK'=0;;;0;1 'Errors'=0;1;1;0;1 'Warnings'=1;1;;0;1 'Unknown'=0;;;0;1
[WARNING]  No PHP Version found online. Your version: 7.1.0

Would it be possible to avoid this somehow? Not very good if you just upgraded and get errors :)

PS: Do you have an icinga2 check command by any chance ? :)

**Comment by cytopia** [comment]
Hmm, looks like I will have to alter the api call for php 7.1
You can omnit `-u` until its fixed. I will have a look.

Can u open up a different issue for icinga2 and provide some more infos please.

**Comment by HOSTED-POWER** [comment]
Hi,

Thanks for the quick response! :)

I think 7.0 has the same problem, as far as I can see you hardcoded version 5.x in the check for new version ...

**Comment by cytopia** [comment]
Hi @HOSTED-POWER 

Can you checkout branch`hotfix/php-version` and see if it works now for your versions.

**Comment by HOSTED-POWER** [comment]
It seems to work fine. Tested on 7.0.14 and 7.1.0! :)

Thanks a lot!!
