### ISSUE TITLE
check_php potentially doesn't see startup errors

### ISSUE THREAD

**Issue by HOSTED-POWER** [cytopia/check_php#3]
Hi,

Depending on the ini used the startup errors don't show. I have this situation by default with cPanel php and easyapache4. With the current version it simply says no errors while I had errors!

Changing this part of the code fixed it and will (most likely) always catch the errors:

```
# Make sure not to display any errors to stdout
# and store them in a variable to output it in a formated way.
check_startup_errors() {
	CMD="$PHP -d display_errors=stderr -d display_startup_errors=1 -v 3>&1 1>&2 2>&3 1>/dev/null"

```

**Comment by HOSTED-POWER** [comment]
Hi,

Any update on this? Really need it for default php setup over here :)

**Comment by HOSTED-POWER** [comment]
Hi, still no update ? :|

**Comment by cytopia** [comment]
Can you checkout branch `PHP-003` and see if it solves your problem.

**Comment by HOSTED-POWER** [comment]
I just tested it and it works perfectly now, thanks a lot!

**Comment by cytopia** [comment]
Merged
