### ISSUE TITLE
Allow passing in PHP binary path

### ISSUE THREAD

**Issue by MarioSteinitz** [cytopia/check_php#5]
This is to suggest to allow passing in the path to the PHP binary to use (e.g. by adding an optional `-p` parameter).

Background: We're using your script on some web servers having multiple PHP versions available that can be used for our virtual hosts. Each version is placed within an `/opt/php/MAYOR.MINOR.PATCH` folder, whereas the latest `MAYOR.MINOR` version on the system has an according symlink and is the default version used for most virtual hosts.

Now we'd love to check all `MAYOR.MINOR` versions on the server for possible security patches available, by e.g. calling your script like `check_php -p /opt/php/5.6/bin/php -u w`.

**Comment by MarioSteinitz** [comment]
We might provide an according MR within the next days.

**Comment by cytopia** [comment]
Good idea.

**Comment by MarioSteinitz** [comment]
Please find PR #6, that adds the above suggested option.

**Comment by cytopia** [comment]
I will close this issue as it has finally been merged. Thanks for the PR.
