### ISSUE TITLE
Increase number of fetched versions on update check

### ISSUE THREAD

**Issue by MarioSteinitz** [cytopia/check_php#7]
While it is desirable to always using up-to-date PHP versions, some servers still run with legacy versions that _might_ get security patches even they aren't supported anymore.

Therefore, the script should fetch a longer version history when doing the version update checks, not only the latest two version updates.

(Increase the `max=2` URL parameter to like `max=50` or so.)

**Comment by cytopia** [comment]
I will close this issue as it has finally been merged. Thanks for the PR.
