### ISSUE TITLE
Version check not working as expected

### ISSUE THREAD

**Issue by MarioSteinitz** [cytopia/check_php#8]
Neither `sort -u`, nor `sort -u -r` within the latest PHP version check is working reliably.

As native `sort` will see e.g. `7.0.9` higher than `7.0.22`.

Newer versions of `sort` feature a `-V` argument for version string sort. However, this argument might not be available on all Unix shells running the script.

Alternatively, the version number string should be split at the dots using the `-t` option of `sort`. Then the keys may be defined and sorted numerical using the `-n` option.

**Comment by cytopia** [comment]
I will close this issue as it has finally been merged. Thanks for the PR.
